---
abstract: 'Perl wrapper for KyTea'
author:
  - 'pawa <pawapawa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  Devel::CheckLib: 0.4
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-KyTea
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Filter::Util::Call: 0
  XSLoader: 0.02
  perl: 5.8.1
resources:
  bugtracker: https://github.com/pawa-/Text-KyTea/issues
  license: http://dev.perl.org/licenses
  repository: https://github.com/pawa-/Text-KyTea
version: 0.04
